version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network

  redis:
    image: redis:7-alpine
    container_name: task_management_redis
    ports:
      - "6379:6379"
    networks:
      - task_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_management_backend
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/taskmanagement?schema=public
      - REDIS_URL=redis://redis:6379
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - task_network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_management_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - task_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  task_network:
    driver: bridge